updating github action to include ggshield and docker build

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,11 +24,21 @@ jobs:
     name: Docker Build
     runs-on: ubuntu-latest
     needs: scanning
-    if: success() # Only execute if the "GitGuardian Scan" job was successful
+    if: ${{ always() && needs.scanning.result == 'success' }} # Only execute if the "GitGuardian Scan" job was successful
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Build Docker image
         run: docker build -t my-django-app .
+        # Replace "my-django-app" with your desired image name
+
+      - name: Run Docker Container (if image built)
+        run: |
+          if docker run -d -p 8000:8000 my-django-app; then
+            echo "Docker container started successfully."
+          else
+            echo "Failed to start Docker container."
+            exit 1
+          fi
         # Replace "my-django-app" with your desired image name
