add jfrog for static code analysis

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,9 +19,18 @@ jobs:
           GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
           GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
           GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
+      
+      - name: Display GitGuardian Scan Result
+        run: |
+          if [ ${{ steps.gitguardian.outputs.success }} == 'true' ]; then
+            echo "GitGuardian scan succeeded."
+          else
+            echo "GitGuardian scan failed."
+            exit 1
+          fi
 
-  build-and-scan:
-    name: Docker Build and JFrog Xray Scan
+  build:
+    name: Docker Build 
     runs-on: ubuntu-latest
     needs: scanning
     if: ${{ always() && needs.scanning.result == 'success' }} # Only execute if the "GitGuardian Scan" job was successful
@@ -33,18 +42,27 @@ jobs:
         run: docker build -t my-django-app .
         # Replace "my-django-app" with your desired image name
 
-      - name: JFrog Xray Scan
+      - name: Display Docker Build Result
         run: |
-          # Run JFrog Xray code analysis on the Docker image
-          # Replace with your actual JFrog Xray scan command
-          # Example: jfrog xray scan my-django-app:latest
-          # Ensure you have JFrog CLI and appropriate authentication set up
-          echo "Running JFrog Xray code analysis..."
-        # You may need to install and configure the JFrog CLI here
+          if [ $? -eq 0 ]; then
+            echo "Docker image build succeeded."
+          else
+            echo "Docker image build failed."
+            exit 1
+          fi
 
-      - name: Run Tests
+      - name: Armo Image Vulnerability Scan
+        if: success() # Only run if the Docker image build was successful
         run: |
-          # Example: Run tests that access the Django app using host.docker.internal
-          curl http://host.docker.internal:8000
-        # Replace with your actual test commands
+          # Install the Armo CLI tool (make sure you have the CLI tool and appropriate authentication set up)
+          curl -s https://get.armo.io | bash
+          # Replace with the command to run the Armo image vulnerability scan
+          # Example: armo scan my-django-app:latest
+          armo scan my-django-app:latest
 
+      - name: Display Armo Scan Result
+        if: success() # Only display if the Armo image vulnerability scan was successful
+        run: |
+          # Replace with the command to display the Armo scan results
+          # Example: armo results
+          echo "Armo image vulnerability scan succeeded."
