testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,13 +6,16 @@ jobs:
   scanning:
     name: GitGuardian Scan
     runs-on: ubuntu-latest
+    outputs:
+      scanning-success: ${{ steps.scanning.outputs.success }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # fetch all history so multiple commits can be scanned
+
       - name: GitGuardian scan
-        id: gitguardian
+        id: scanning
         uses: GitGuardian/ggshield-action@v1.20.0
         env:
           GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
@@ -24,7 +27,7 @@ jobs:
     name: Docker Build
     runs-on: ubuntu-latest
     needs: scanning
-    if: ${{ always() && needs.scanning.result == 'success' }} # Only execute if the "GitGuardian Scan" job was successful
+    if: ${{ needs.scanning.outputs.scanning-success == 'true' }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -33,12 +36,21 @@ jobs:
         run: docker build -t my-django-app .
         # Replace "my-django-app" with your desired image name
 
-jobs:
+      - name: Run Docker Container (if image built)
+        run: |
+          if docker run -d -p 8000:8000 my-django-app; then
+            echo "Docker container started successfully."
+          else
+            echo "Failed to start Docker container."
+            exit 1
+          fi
+        # Replace "my-django-app" with your desired image name
+
   vulnerability_scan:
     name: Check for Image Vulnerabilities
     runs-on: ubuntu-latest
     needs: build
-    if: ${{ always() && needs.build.result == 'success' }} # Only run if the Docker image build was successful
+    if: ${{ needs.build.result == 'success' }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
